id: {{gen_salt(8)}}
name: {{project}}
app:
  host: 127.0.0.1
  port: 3000
  debug: false
databases:
  mongo:
    alias: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: ""
    database: test
  mysql:
    alias: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: ""
    database: test
celery:
  worker: 4
switch:
  cron:
    report_daily: False
